# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-25 11:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('telphone', models.CharField(max_length=20, unique=True, verbose_name='telephone number')),
                ('nickName', models.CharField(max_length=32, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('avatar', models.CharField(blank=True, max_length=256, null=True)),
                ('sex', models.CharField(choices=[('male', '男'), ('female', '女')], default='male', max_length=16)),
                ('friens', models.ManyToManyField(blank=True, related_name='_myuser_friens_+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
